---
  - name: Download the wallpaper image
    get_url:
      url: "https://cdn.eso.org/images/screen/eso0932a.jpg"
      dest: "/home/andrew/.wallpaper.jpg"
  
  - name: Set GNOME Wallpaper
    become_user: andrew
    dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/andrew/.wallpaper.jpg'"
    
  - name: Set GNOME Wallpaper scale
    become_user: andrew
    dconf: key="/org/gnome/desktop/background/picture-options" value="'scaled'"
 
  - name: Set 24 Hour Clock
    become_user: andrew
    dconf: key="/org/gnome/desktop/interface/clock-format" value="'24h'"

  - name: Set Clock Show Weekday
    become_user: andrew
    dconf: key="/org/gnome/desktop/interface/clock-show-weekday" value="'true'"

  - name: Set Top Bar Show Battery Percentage
    become_user: andrew
    dconf: key="/org/gnome/desktop/interface/show-battery-percentage" value="'true'"
