---
  - name: Download the wallpaper image
    become_user: andrew
    get_url:
      url: "https://cdn.eso.org/images/screen/eso0932a.jpg"
      dest: "/home/andrew/Pictures/wallpaper.jpg"

  - name: Set GNOME wallpaper
    become_user: andrew
    command: >
      gsettings set org.gnome.desktop.background picture-uri file:///home/andrew/Pictures/wallpaper.jpg

  - name: Set 24 Hour Clock
    become_user: andrew
    dconf: key="/org/gnome/desktop/interface/clock-format" value="'24h'"

  - name: Set Clock Show Weekday
    become_user: andrew
    dconf: key="/org/gnome/desktop/interface/clock-show-weekday" value="'true'"

  - name: Set Top Bar Show Battery Percentage
    become_user: andrew
    dconf: key="/org/gnome/desktop/interface/show-battery-percentage" value="'true'"
