- name: install cron job (ansible-pull-client-system)
  cron:
    user: svc_ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/arunstedler/AnsiblePullClientSystem.git > /dev/null"
