- name: Install packages
  apt:
    name:
      - htop
      - tmux
      - krita
      - google-chrome-stable
      - gimp
      - kdenlive
      - gnome-shell-extension-prefs
      - gedit-plugins
      - gnome-tweaks
      - gnome-sushi
      - gnome-session
      - chrome-gnome-shell

- name: Install packages
  snap:
    name:
      - freecad
